services:
  laravel-app:
    build:
      context: .
      dockerfile: docker/dev/php/php.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/isc-admin-api/src:/var/www/html
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"  
    networks:
      - proxy_network

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - /home/abdallah644/projects/my-projects/isc-admin-api/src:/var/www/html
      - /home/abdallah644/projects/my-projects/isc-admin-api/docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_network

  artisan:
    build:
      context: /home/abdallah644/projects/my-projects/isc-admin-api/src
      dockerfile: /home/abdallah644/projects/my-projects/isc-admin-api/docker/dev/artisan/artisan.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/isc-admin-api/src:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - laravel-app

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - /home/abdallah644/projects/my-projects/isc-admin-api/src:/app
    working_dir: /app
    command: install
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true

volumes:
  mssql_data:
