services:
  laravel-app:
    build:
      context: .
      dockerfile: docker/php/php.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/laravel.mssql/src:/var/www/html
    networks:
      - proxy_network

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - /home/abdallah644/projects/my-projects/laravel.mssql/src:/var/www/html
      - /home/abdallah644/projects/my-projects/laravel.mssql/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy_network

  artisan:
    build:
      context: /home/abdallah644/projects/my-projects/laravel.mssql/src
      dockerfile: /home/abdallah644/projects/my-projects/laravel.mssql/docker/artisan/artisan.dockerfile
    volumes:
      - /home/abdallah644/projects/my-projects/laravel.mssql/src:/var/www/html
    networks:
      - proxy_network
    depends_on:
      - laravel-app

networks:
  proxy_network:
    external: true

volumes:
  mssql_data:
